---
- name: "update apt packages."
  become: true
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: true
  apt:
    upgrade: yes

# - name: "Install dependencies"
#   become: true
#   apt:
#     pkg:
#       - nodejs
#       - npm
#     state: latest
#     update_cache: true



- name: "Install Node.js 13"
  shell: |
    # Install Node.js LTS version as our base Node.js version
    curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
    sudo apt-get install -y nodejs

    # Use n version manager to use Node.js v13.8.0
    sudo npm install -g n
    sudo n 13.8.0


- name: "Install pm2"
  become: true
  ansible.builtin.command:
    cmd: npm install pm2 -g

- name: "Install PM2 Globally"
  npm:
    name: pm2
    global: yes
